### ISSUE TITLE
MVP data for Saturday

### ISSUE THREAD

**Issue by jpasila** [NuCivic/dkan-ebola#12]
- [ ] MVP data to include: what data would you want to see and how much that would make a compelling demo (Stefanie will determine) ‘easy + good’ to meet MVP.
- [ ] Stefanie will check what is already on eboladata.org. Andrew will check with Stefanie Thursday and Friday.

**Comment by stefaniefgray** [comment]
Ran this by Andrew this afternoon. Data looks good to go!
