### ISSUE TITLE
documentation: how to publish data

### ISSUE THREAD

**Issue by watsonerror** [NuCivic/dkan-ebola#14]
Please write a quick instruction set on how to publish data.

**Comment by stefaniefgray** [comment]
https://docs.google.com/document/d/18f2C22xnOGFKsCJRu3yC3GgnzkIYz5_YiI0l5sUVo1E/edit

How does this look? Once I get the go-ahead, I'll put this up as a separate page (and can adapt it for EbolaData.org, Sierra Leone and Liberia.)

**Comment by andrewhoppin** [comment]
Awesome!
