### ISSUE TITLE
Email on which data to add and to keep from Saska and Dennis at IBM

### ISSUE THREAD

**Issue by stefaniefgray** [NuCivic/dkan-ebola#19]
"Hi Stefanie,

Great to hear that you're already hard at work on this.  I took a look through the existing data sources on eboladata.org and the following names stood out as more relevant for the jam.  Let us know if you find others.

Healthcare facility data
Sierra Leone Health Facilities
Ebola Treatment Centers or Units - official UNMEER data, at least as of a few months ago
Standby Task Force - all sorts of crowd-sourced maps of health facilities and related data
UK redcross data on cases, deaths, treatment centers - possibly superseded by Ebola Treatment Centers or Units above
Ebola Treatment Centres, Isolation Wards, Hospitals and Transit Centres - superseded by Ebola Treatment Centers or Units above

More generally you could search for Simon B. Johnson of the UK Red Cross.  He's responsible for a good part of the data and visualizations above as well as many others.

Sierra Leone
Sierra Leone Open Government Initiative - don't know what they already have up
Sierra Leone Ministry of Health and Sanitation
Sierra Leone official regional statistics - may be useful for mapping/visualization

Other
Humanitarian Data Exchange - seems to be the major data repository for humanitarian workers

3 PDFs from Steve Adler
(See attached file: List of Clinics _ SIERRA LEONE NATIONAL CLUBFOOT PROGRAM.pdf)(See attached file: Hospitals - Informations and Contacts Sierra Leones Site.pdf)(See attached file: 03092013-MedicalServiceProvidersApril2013.pdf)

In addition, we have a bunch of offline PDFs, spreadsheets, and the like from Richard Garfield of the US CDC but need to spend some time to sort through them. 

Dennis"

Currently transcribing the PDFs

**Comment by jvitello** [comment]
Stefanie, I think this ticket isn't needed anymore. Can we close?
