### ISSUE TITLE
Blocker: Sierra Leone live site is down, not enough privileges to edit Liberia.

### ISSUE THREAD

**Issue by stefaniefgray** [NuCivic/dkan-ebola#20]

**Comment by jonpugh** [comment]
whoah!
Not down, just moved?  Try http://live.data.sierraleone.nucivic.build/

**Comment by stefaniefgray** [comment]
Whew, thanks for letting me know!

**Comment by jonpugh** [comment]
I thought I setup a redirect!  sorry about that.

**Comment by jonpugh** [comment]
@stefaniefgray Try now on liberia. Admin perms should be fully set.
