### ISSUE TITLE
Missing left column on Datasets after upgrading to 1.7

### ISSUE THREAD

**Issue by andrewhoppin** [NuCivic/dkan-ebola#25]
After upgrading EbolaData.org to v1.7 /datset pages had no left column.  @sheldonrampton had to go in and manually enable the node template at http://eboladata.org/admin/structure/panels

**Comment by andrewhoppin** [comment]
dafeder [11:58 AM] 
ok - think the disabled node template was a bug in the upgrade?

jonpugh [11:58 AM] 
and janette

sheldonrampton [11:58 AM] 
I don't know.

dafeder [11:58 AM] 
I'm guessing it was by design since an existing 1.6 site might break if you force enabled the node template

ahoppin [12:26 PM]
@dafeder: re "I'm guessing it was by design since an existing 1.6 site might break if you force enabled the node template" -- may be by design, but bad user experience-- in this case we'd at least want to publish an "upgrade checklist" to unbreak things that break, IMO

**Comment by andrewhoppin** [comment]
Also missing on http://eboladata.org/node/add/dataset

**Comment by acouch** [comment]
Was panels already turned on? Was panels turned off after the upgrade? @drkloc lets share the docs for this as we didn't get a chance before Friday.

**Comment by jonpugh** [comment]
I have to ask @janette, but I think it is possible Panels was not turned on during the upgrade... I could be wrong.  Friday night is a bit of a blur.

@andrewhoppin I enabled the node/edit panel which added the help block to that page.

That pane needs a special variable to be set to be enabled.  Not sure if DKAN should have that or not.
