### ISSUE TITLE
Dataset node edit accordian field options not working

### ISSUE THREAD

**Issue by andrewhoppin** [NuCivic/dkan-ebola#28]
![authoring_options]
![menus](https://cloud.githubusercontent.com/assets/1126274/6315583/34d4b338-b9d4-11e4-8705-458fe38f9188.png)

see attached.... can't expand or contract field option menus

**Comment by acouch** [comment]
I'm not seeing this on the demo site so don't think it is release specific.

**Comment by andrewhoppin** [comment]
I don't see accordian menus on demo.getdkan.com at all.  Why would EbolaData.org have them?   My concern (other than fixing EbolaData.org) is that other live DKAN sites, when upgrading to 1.7, might experience similar issues, even if our own testing on demo.getdkan.com come out clean...

**Comment by jonpugh** [comment]
Looks like something Javascript is breaking, preventing the expanding fieldsets.

Could also be the cause of #30...

Found the cuprit: 

```
http://eboladata.org/profiles/dkan/libraries/Leaflet/dist/leaflet-src.js?v=6 Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by jonpugh** [comment]
Was wondering why that JS file wasn't 

Turns out it was gitignore in the leaflet library.

```
The following paths are ignored by one of your .gitignore files:
profiles/dkan/libraries/Leaflet/dist/leaflet-src.js
```

@drkloc we need a good way of dealing with these .gitignores...

**Comment by jonpugh** [comment]
Ok, the file was deployed making the fieldsets change into vertical tabs fieldsets.

@acouch The problem was that leaflet was set to gitignore it's own `dist/leaflet-src.js` file, so when I copied down the new release, it was never added to the eboladata.org git repo.

I need to flag this somewhere with the DKAN team, there are a lot of libraries and gitignore files out there that make it hard to update a site.

**Comment by jonpugh** [comment]
Waiiit i i think i know the problem.  I was just looking at NuCivic/data_starter's Leaflet directory and I am not seeing a .gitignore.

It must have been left over from the original eboladata.org.

@acouch should we add something about this to the DKAN release notes?
