### ISSUE TITLE
Content / Data to transfer to SL and L portals

### ISSUE THREAD

**Issue by jpasila** [NuCivic/dkan-ebola#3]
What data could / should be moved over from Eboladata.org. Stefanie to connect with Sashka. More content than data that tells the story of why this work is important. If we can make this more ‘real’ towards all stakeholders - eboladata.org links

**Comment by stefaniefgray** [comment]
Reached out to Saska, waiting to hear back.

**Comment by stefaniefgray** [comment]
Issue has Saska and Dennis's response #19
