### ISSUE TITLE
strange node edit UI

### ISSUE THREAD

**Issue by andrewhoppin** [NuCivic/dkan-ebola#30]
![edit_dataset_sierra_leone_health_facilities___eboladata_org](https://cloud.githubusercontent.com/assets/1126274/6315942/8e90c1bc-b9e0-11e4-8e4c-4d8f5f3e9b4e.png)

**Comment by jonpugh** [comment]
Labelling for DKAN team.  Still looks like this after enabling the node edit panel.

**Comment by jonpugh** [comment]
All fixed! It was the missing leaflet library.
