### ISSUE TITLE
Every file download link is broken

### ISSUE THREAD

**Issue by stefaniefgray** [NuCivic/dkan-ebola#35]
Tried accessing multiple files through both the Datasets interface and the Files listing. I can't download any of the PDFs or CSVs that worked perfectly fine in the past.

I can view the Recline previews of certain CSVs such as http://www.eboladata.org/dataset/ebola-testing-laboratories/resource/9539c522-717c-4250-ab56-15b3637cf43b#{view-map:{geomField:!Location}}

However, there is no way to download the original file: The requested page "/sites/live.data.eboladata.nucivic.build/files/Laboratories.csv" could not be found.

Changing the URL path to live.data.eboladata.nucivic.build/files/Laboratories.csv or http://www.eboladata.org/files/Laboratories.csv did not work.

**Comment by jonpugh** [comment]
Some of the files that had the old URL in them (live.ebola.softlayer.devshop.build) will now work.

Some are still missing, and I don't think there's anything I can do about that if they are not on the server...

Unless...  didn't we setup backups?  @grantdobbe Are the files for eboladata.org being backed up?

@grantdobbe can you help @stefaniefgray find files like http://www.eboladata.org/sites/live.data.eboladata.nucivic.build/files/Laboratories.csv ?

Sorry I couldn't do more. I'm not sure what could have happened to them.  We synced everything over.

**Comment by grantdobbe** [comment]
I have backups from 11 March to this morning.

**Comment by jonpugh** [comment]
@grantdobbe Is this file in there, perhaps?  http://www.eboladata.org/sites/live.data.eboladata.nucivic.build/files/Laboratories.csv 

Should we just copy what we have in backups back into the server?

**Comment by grantdobbe** [comment]
It's not in last night's fileset. I'll go back a few days and see if I can find it.

**Comment by grantdobbe** [comment]
I was mistaken. It is in last night's file set.
I'll restore.

**Comment by grantdobbe** [comment]
Files have been restored, try it now.
