### ISSUE TITLE
Views security bug fix

### ISSUE THREAD

**Issue by jvitello** [NuCivic/dkan-ebola#40]
There is a security bug with Views that is currently being addressed by an update to the Views module in DKAN.

NuCivic/dkan#453

Once this is complete and tested, the Softlayer sites can be updated.

**Comment by jvitello** [comment]
J, assigning this to you since you are the scrum master for Neptune. Since MyNuCivic is going to be under Neptune, I think you will own the ebola-data site. Let me know if you think otherwise.

**Comment by jpasila** [comment]
@acouch Grant's understanding was that this was fixed at the retreat but apparently not - please reach out to him or Jon for any questions

**Comment by Krista-Nuams** [comment]
what happened with this?

**Comment by jpasila** [comment]
see: https://huboard.com/NuCivic/mynucivic#/
