### ISSUE TITLE
Assign someone for tech support for Saturday

### ISSUE THREAD

**Issue by jpasila** [NuCivic/dkan-ebola#5]
NuCivic to provide some tech support

**Comment by jpasila** [comment]
@andrewhoppin do we have anyone available for this role? I know Stefanie and you are online but do we need Aaron or ...?

**Comment by andrewhoppin** [comment]
---------- Forwarded message ----------
From: Raya Horesh rhoresh@us.ibm.com
Date: Thu, Feb 19, 2015 at 2:05 PM
Subject: Re: few logistics details for NYC Jam this Saturday
To: Andrew Hoppin andrew@nucivic.com
Cc: Aleksandra Mojsilovic aleksand@us.ibm.com, andrew@nuams.co, Dennis Wei dwei@us.ibm.com, Kush R Varshney krvarshn@us.ibm.com, Martin J Laird lairdmar@us.ibm.com, Martin J Sepulveda mjs851@us.ibm.com, Stefanie Gray stefanie@nucivic.com, Steven Adler adler1@us.ibm.com

I am glad to assist!

See you there on Saturday.

Raya

```
Raya Horesh. PhD
```

Research Scientist
Numerical Methods Group
Business Analytics and Mathematical Sciences

Phone: +1 914 945 2772
E-mail: rhoresh@us.ibm.com
IBM

IBM TJ Watson Research Center
1101 Kitchawan Road, Yorktown Heights
New York, USA 10598

Inactive hide details for Andrew Hoppin ---02/19/2015 12:37:34 PM---Fantastic.  Thank you Raya and Aleksandra!  Raya, we can trAndrew Hoppin ---02/19/2015 12:37:34 PM---Fantastic.  Thank you Raya and Aleksandra!  Raya, we can train you on account management first thing

From:   Andrew Hoppin andrew@nucivic.com
To: Aleksandra Mojsilovic/Watson/IBM@IBMUS
Cc: Steven Adler/Somers/IBM@IBMUS, Stefanie Gray stefanie@nucivic.com, Dennis Wei/Watson/IBM@IBMUS, Kush R Varshney/Watson/IBM@IBMUS, Martin J Laird/New York/IBM@IBMUS, Martin J Sepulveda/Somers/IBM@IBMUS, Raya Horesh/Watson/IBM@IBMUS
Date:   02/19/2015 12:37 PM

Subject:    Re: few logistics details for NYC Jam this Saturday
Sent by:    andrew@nuams.co

Fantastic.  Thank you Raya and Aleksandra!  Raya, we can train you on
account management first thing on Saturday.

**Comment by andrewhoppin** [comment]
Not a technical role-- we can train Raya easily.
