### ISSUE TITLE
'How to' document for Saturday Jam

### ISSUE THREAD

**Issue by jpasila** [NuCivic/dkan-ebola#6]
NuCivic to provide overview of how to create an archive that can then be made public.

**Comment by stefaniefgray** [comment]
https://docs.google.com/a/nuams.co/document/d/18f2C22xnOGFKsCJRu3yC3GgnzkIYz5_YiI0l5sUVo1E/edit

Added this document as a separate page to EbolaData.org. (Still having issues with the formatting not showing up though -- see https://github.com/NuCivic/nucivic-internal/issues/407
