### ISSUE TITLE
George please create separate tickets for these

### ISSUE THREAD

**Issue by jpasila** [NuCivic/dkan-ebola#9]
- [x] update text in hero image area
- [x] documentation: how to publish data
- [x] nice to have: chat window for support a la DOT
- [x] have portals looking good but won’t be launching on Saturday
- [x] MVP data to include: what data would you want to see and how much that would make a compelling demo (Stefanie will determine) ‘easy + good’ to meet MVP.
- [x] Stefanie will check what is already on eboladata.org. Andrew will check with Stefanie Thursday and Friday.

**Comment by jpasila** [comment]
closing as duplicate

**Comment by watsonerror** [comment]
I'm not sure what "have portals looking good but won’t be launching on Saturday" means so I'm assuming it's not important because of how unclear it is.

**Comment by watsonerror** [comment]
RE: MVP data: Stefanie is working with IBM / Saska about what data to include.
